trigger:
  - none

pr:
  - none

variables:
  - template: /eng/pipelines/common/variables.yml

resources:
  repositories:
    - repository: xamarin-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main # still defaults to master even though main is the main branch
  pipelines:
    - pipeline: handlersci
      source: xamarin-handlers-ci
      trigger: 
        branches:
          - main
          - main-handlers
          - dev/ci-device-tests

stages:
  - stage: test_android
    displayName: Android
    dependsOn: []
    jobs:
      - job: device_tests
        workspace:
          clean: all
        displayName: Device Tests
        timeoutInMinutes: 120
        pool:
          name:  $(macOSXVmPool)
          vmImage: $(macOSXVmImage)
        variables:
          provisionator.xcode : '$(System.DefaultWorkingDirectory)/eng/provisioning/xcode.csx'
          provisionator.path : '$(System.DefaultWorkingDirectory)/eng/provisioning/provisioning.csx'
          provisionator.extraArguments : '--v'
          ANDROID_EMULATORS: "system-images;android-30;google_apis_playstore;x86"
        strategy:
          matrix:
            Essentials:
              project: '$(System.DefaultWorkingDirectory)/src/Essentials/test/DeviceTests.Android/Xamarin.Essentials.DeviceTests.Android.csproj'
            Handlers:
              project: '$(System.DefaultWorkingDirectory)/src/Platform.Handlers/tests/Xamarin.Platform.Handlers.DeviceTests.Android/Xamarin.Platform.Handlers.DeviceTests.Android.csproj'
        steps:
          - template: common/device-tests-android.yml
